# Generated by Django 5.0.12 on 2025-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('categoria', models.CharField(choices=[('BC', 'bache'), ('AL', 'alumbrado'), ('BA', 'basura'), ('OT', 'otro')], max_length=100)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
    ]
